// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciAidatSistemi.Data;

#nullable disable

namespace OgrenciAidatSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("OgrenciAidatSistemi.Models.FilePath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilePath");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentPeriodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentPeriodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");

                    b.HasDiscriminator<string>("PaymentType").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.PaymentPeriode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Occurence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentPeriods");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.BankTransferPayment", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.Payment");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Payments", t =>
                        {
                            t.Property("BankName")
                                .HasColumnName("BankTransferPayment_BankName");

                            t.Property("BranchCode")
                                .HasColumnName("BankTransferPayment_BranchCode");
                        });

                    b.HasDiscriminator().HasValue("BankTransferPayment");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.CashPayment", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.Payment");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ReceiptId");

                    b.HasDiscriminator().HasValue("Cash");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.CheckPayment", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.Payment");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CheckPayment");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.CreditCardPayment", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.Payment");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Payments", t =>
                        {
                            t.Property("CVC")
                                .HasColumnName("CreditCardPayment_CVC");

                            t.Property("CardHolderName")
                                .HasColumnName("CreditCardPayment_CardHolderName");

                            t.Property("CardNumber")
                                .HasColumnName("CreditCardPayment_CardNumber");

                            t.Property("ExpiryDate")
                                .HasColumnName("CreditCardPayment_ExpiryDate");
                        });

                    b.HasDiscriminator().HasValue("CreditCard");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.DebitCardPayment", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.Payment");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DebitCardPayment");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.SchoolAdmin", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("SchoolId")
                                .HasColumnName("SchoolAdmin_SchoolId");
                        });

                    b.HasDiscriminator().HasValue("SchoolAdmin");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.SiteAdmin", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.User");

                    b.HasDiscriminator().HasValue("SiteAdmin");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.Student", b =>
                {
                    b.HasBaseType("OgrenciAidatSistemi.Models.User");

                    b.Property<int>("GradLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SchoolId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.Payment", b =>
                {
                    b.HasOne("OgrenciAidatSistemi.Models.PaymentPeriode", "PaymentPeriode")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentPeriodeId");

                    b.HasOne("OgrenciAidatSistemi.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentPeriode");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.CashPayment", b =>
                {
                    b.HasOne("OgrenciAidatSistemi.Models.FilePath", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.SchoolAdmin", b =>
                {
                    b.HasOne("OgrenciAidatSistemi.Models.School", "_School")
                        .WithMany("SchoolAdmins")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_School");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.Student", b =>
                {
                    b.HasOne("OgrenciAidatSistemi.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.PaymentPeriode", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("OgrenciAidatSistemi.Models.School", b =>
                {
                    b.Navigation("SchoolAdmins");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
